### ISSUE TITLE
Can't easily assimilate ?

### ISSUE THREAD

**Issue by Noctis-** [PageUpPeopleOrg/SeriLog.LogSanitizingFormatter#3]
Hi guys, this is a .Net Core project, so can't really be used or added to a normal project (unless i'm missing something basic here).

Won't install with nuget, and won't be able to import dll directly as well.

**Comment by nblumhardt** [comment]
Just checking out the `project.json`, I think this'd work happily with .NET 4.x if `netcoreapp1.0` on [this line](https://github.com/PageUpPeopleOrg/SeriLog.LogSanitizingFormatter/blob/master/src/SeriLog.LogSanitizingFormatter/project.json#L14) was changed to `netstandard1.5` or lower.

**Comment by humblelistener** [comment]
this is due for framework and tool upgrade for a while now. Will get to this asap.

**Comment by Noctis-** [comment]
THEY'RE ALIVE :) 
awesome ... I'll keep an eye open 👍

**Comment by humblelistener** [comment]
@terencet I updated the code but don't have permissions to publish it. Can you publish it for the time being?

**Comment by terencetham** [comment]
@humblelistener @Noctis- I've just published the update package to nuget

**Comment by humblelistener** [comment]
:thumbsup:

**Comment by humblelistener** [comment]
I am closing the issue for the moment. Happy for you guys to reopen it if you had more reasons @noctis & @nblumhardt
